AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: Include, TreatCommentsAsGroupSeparators.
# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 48
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'features/step_definitions/login_steps.rb'
    - 'features/step_definitions/sendmessage_steps.rb'
    - 'features/step_definitions/web_steps.rb'

# Offense count: 1
# Cop supports --auto-correct.
Lint/Debugger:
  Exclude:
    - 'features/step_definitions/web_steps.rb'

# Offense count: 1
Lint/HandleExceptions:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: IgnoreEmptyBlocks, AllowUnusedKeywordArguments.
Lint/UnusedBlockArgument:
  Exclude:
    - 'features/step_definitions/login_steps.rb'
    - 'features/step_definitions/sendmessage_steps.rb'

# Offense count: 3
Metrics/AbcSize:
  Max: 25

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
  Max: 114

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 10

# Offense count: 89
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 173

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 24

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 10

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, SupportedHashRocketStyles, EnforcedColonStyle, SupportedColonStyles, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/AlignHash:
  Exclude:
    - 'features/step_definitions/login_steps.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  Exclude:
    - 'spec/views/email_contacts/new.html.erb_spec.rb'
    - 'spec/views/email_contacts/show.html.erb_spec.rb'
    - 'spec/views/email_contacts/thankyou.html.erb_spec.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: always, conditionals
Style/AndOr:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 2
# Cop supports --auto-correct.
Layout/ClosingParenthesisIndentation:
  Exclude:
    - 'spec/views/email_contacts/new.html.erb_spec.rb'
    - 'spec/views/email_contacts/show.html.erb_spec.rb'

# Offense count: 16
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: native, lf, crlf
Layout/EndOfLine:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment, ForceEqualSignAlignment.
Layout/ExtraSpacing:
  Exclude:
    - 'config.ru'
    - 'db/schema.rb'
    - 'script/rails'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues, PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
Style/HashSyntax:
  Exclude:
    - 'lib/gmail_smtp/lib/actionmailer_gmail.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces
Layout/IndentHash:
  Exclude:
    - 'lib/gmail_smtp/lib/actionmailer_gmail.rb'

# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: Width, IgnoredPatterns.
Layout/IndentationWidth:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'
    - 'lib/tasks/cucumber.rake'

# Offense count: 4
# Cop supports --auto-correct.
Layout/LeadingCommentSpace:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Exclude:
    - 'features/support/paths.rb'
    - 'features/support/selectors.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - 'spec/views/email_contacts/new.html.erb_spec.rb'
    - 'spec/views/email_contacts/show.html.erb_spec.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineOperationIndentation:
  Exclude:
    - 'features/support/paths.rb'
    - 'features/support/selectors.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/Not:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'features/step_definitions/login_steps.rb'
    - 'features/step_definitions/web_steps.rb'
    - 'lib/tasks/cucumber.rake'

# Offense count: 2
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Exclude:
    - 'features/support/paths.rb'
    - 'features/support/selectors.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'features/support/paths.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'features/step_definitions/web_steps.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/SpaceAfterComma:
  Exclude:
    - 'features/step_definitions/web_steps.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: space, no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'lib/gmail_smtp/lib/actionmailer_gmail.rb'
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 59
# Cop supports --auto-correct.
Layout/Tab:
  Exclude:
    - 'lib/gmail_smtp/lib/actionmailer_gmail.rb'
    - 'lib/gmail_smtp/lib/smtp_tls.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowSafeAssignment.
# SupportedStyles: require_parentheses, require_no_parentheses, require_parentheses_when_complex
Style/TernaryParentheses:
  Exclude:
    - 'features/step_definitions/web_steps.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStylesForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInLiteral:
  Exclude:
    - 'lib/gmail_smtp/lib/actionmailer_gmail.rb'
